name: Test

on:
  push: # Run whenever the Build workflow completes
    branches: [main]
  workflow_dispatch: # Enables manual triggering

jobs:

  test:
    
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out database branch
        uses: actions/checkout@v4
      - name: Set up Node runtime
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          check-latest: false
          cache: npm
      - name: Install dependencies
        run: npm ci # Clean, frozen install. Doesn't modify package.json or package-lock.json
      - name: Run tests
        run: npm test
